### ISSUE TITLE
GUI labels

### ISSUE THREAD

**Issue by ironcrypto** [one7okn/one7okn-html#1]
![Image](https://user-images.githubusercontent.com/31933810/174404741-4d933325-257d-4728-a36c-421fc116f18a.png)

My Option -> "My Options"

CREATE OPTION -> "MINT NEW OPTION"

![Image](https://user-images.githubusercontent.com/31933810/174404890-774ce2e8-c55b-488a-96f6-c2217b559c35.png)

Create a put option -> "Mint a Put Option"

![Image](https://user-images.githubusercontent.com/31933810/174405138-f4415a83-e8fd-47a3-ad2d-76d8d2006093.png)

Strike price (eth) -> "Strike Price (ETH)"
Floor price (eth) -> "Floor Price (ETH)"

![Image](https://user-images.githubusercontent.com/31933810/174405206-56818d33-171f-4705-864d-e54fceaf9f0f.png)

ether -> "ETH"

![Image](https://user-images.githubusercontent.com/31933810/174405260-c090a37d-942b-45bb-ab64-33e4e032f594.png)

BUY -> "MINT"

**Comment by patromain** [comment]
Fix
