### ISSUE TITLE
Collection drop list is empty, need to add collection

### ISSUE THREAD

**Issue by ironcrypto** [one7okn/one7okn-html#2]
Add the following collections to the list, in ascending order:

cryptopunks
quantum-curated
rektguy 
deadfellaz
doodles-official 
goblintownwtf 
mcgoblinwtf 
goblin-grlz 
okaybearsyachtclub 
boredapeyachtclub 
nightcard 
goblinai

**Comment by patromain** [comment]
Maintenant la liste est pleuplé avec les nfts de la personne.
![image](https://user-images.githubusercontent.com/43301301/174446831-c64bdc7f-d44a-45de-a3d2-d90f7c2fe345.png)
