### ISSUE TITLE
nothing happens after minting the option and confirming the transaction on metamask

### ISSUE THREAD

**Issue by ironcrypto** [one7okn/one7okn-html#4]

**Comment by ironcrypto** [comment]
le formulaire reste ouvert. l'option n'est pas visible sur la page My Options

**Comment by patromain** [comment]
C'est juste que c'est long sur ropsten. Ca ma prit 10s je pense.
![image](https://user-images.githubusercontent.com/43301301/174604461-70a09395-b248-4fe6-b7a5-67f8db4efffa.png)
